export const authenticatedSurfaces = [
  { name: "Dashboard", path: "/" },
  { name: "Transactions", path: "/transactions" },
  { name: "Uncategorized inbox", path: "/transactions/inbox" },
  { name: "Deleted transactions", path: "/transactions/deleted" },
  { name: "Assistant", path: "/assistant" },
  { name: "Insights", path: "/insights" },
  { name: "Forecast", path: "/forecast" },
  { name: "Budgets", path: "/budgets" },
  { name: "Digest", path: "/digest" },
  { name: "Categories", path: "/categories" },
  { name: "Tags", path: "/tags" },
  { name: "Recurring", path: "/recurring" },
  { name: "Templates", path: "/templates" },
  { name: "Rules", path: "/rules" },
  { name: "What If", path: "/scenarios" },
  { name: "Reconciliation", path: "/reconciliation" },
  { name: "Report Builder", path: "/reports/builder" },
  { name: "Settings", path: "/settings" },
  {
    name: "Admin elevation",
    path: "/admin/elevate?redirect=%2Fadmin",
  },
] as const
