/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    borderRadius: {
      none: "0",
      xs: "var(--radius-xs)",
      sm: "var(--radius-sm)",
      DEFAULT: "var(--radius-md)",
      md: "var(--radius-md)",
      lg: "var(--radius-lg)",
      xl: "var(--radius-xl)",
      "2xl": "var(--radius-2xl)",
      full: "9999px",
    },
    extend: {
      spacing: {
        sidebar: "224px",
      },
      fontFamily: {
        head: ["system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        sans: ["system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono: ["IBM Plex Mono", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      colors: {
        bg: "rgb(var(--bg) / <alpha-value>)",
        background: "rgb(var(--background) / <alpha-value>)",
        surface: "rgb(var(--surface) / <alpha-value>)",
        "surface-hi": "rgb(var(--surface-hi) / <alpha-value>)",
        border: "rgb(var(--border) / <alpha-value>)",
        "border-hi": "rgb(var(--border-hi) / <alpha-value>)",
        input: "rgb(var(--input) / <alpha-value>)",
        ring: "rgb(var(--ring) / <alpha-value>)",
        text: "rgb(var(--text) / <alpha-value>)",
        foreground: "rgb(var(--foreground) / <alpha-value>)",
        faint: "rgb(var(--faint) / <alpha-value>)",
        muted: "rgb(var(--muted) / <alpha-value>)",
        "muted-foreground": "rgb(var(--muted-foreground) / <alpha-value>)",
        accent: "rgb(var(--accent) / <alpha-value>)",
        "accent-dim": "rgb(var(--accent-soft) / 0.18)",
        "accent-foreground": "rgb(var(--accent-foreground) / <alpha-value>)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        "primary-foreground": "rgb(var(--primary-foreground) / <alpha-value>)",
        secondary: "rgb(var(--secondary) / <alpha-value>)",
        "secondary-foreground": "rgb(var(--secondary-foreground) / <alpha-value>)",
        card: "rgb(var(--card) / <alpha-value>)",
        "card-foreground": "rgb(var(--card-foreground) / <alpha-value>)",
        popover: "rgb(var(--popover) / <alpha-value>)",
        "popover-foreground": "rgb(var(--popover-foreground) / <alpha-value>)",
        destructive: "rgb(var(--destructive) / <alpha-value>)",
        "destructive-foreground":
          "rgb(var(--destructive-foreground) / <alpha-value>)",
        "semantic-green": "rgb(var(--semantic-green) / <alpha-value>)",
        "semantic-red": "rgb(var(--semantic-red) / <alpha-value>)",
        "semantic-blue": "rgb(var(--semantic-blue) / <alpha-value>)",
        "semantic-purple": "rgb(var(--semantic-purple) / <alpha-value>)",
        "signal-blue-soft": "rgb(var(--signal-blue-soft) / <alpha-value>)",
        "signal-green-soft": "rgb(var(--signal-green-soft) / <alpha-value>)",
        "signal-red-soft": "rgb(var(--signal-red-soft) / <alpha-value>)",
        "signal-yellow-soft": "rgb(var(--signal-yellow-soft) / <alpha-value>)",
        "signal-purple-soft": "rgb(var(--signal-purple-soft) / <alpha-value>)",
        emerald: {
          200: "rgb(var(--emerald-200) / <alpha-value>)",
          300: "rgb(var(--emerald-300) / <alpha-value>)",
          400: "rgb(var(--semantic-green) / <alpha-value>)",
          500: "rgb(var(--semantic-green) / <alpha-value>)",
        },
        rose: {
          200: "rgb(var(--rose-200) / <alpha-value>)",
          300: "rgb(var(--rose-300) / <alpha-value>)",
          400: "rgb(var(--semantic-red) / <alpha-value>)",
          500: "rgb(var(--semantic-red) / <alpha-value>)",
        },
      },
      screens: {
        desk: "861px",
      },
    },
  },
  plugins: [],
}
