name: Full tests

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "23 4 * * 1"

permissions:
  contents: read

concurrency:
  group: full-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/ci.yml
